databases:
  - name: tnt_project_management
    databaseName: tnt_project_management
    user: tnt_project_management_user

services:
  - type: web
    name: tnt_project_management_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tnt_project_management
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false